name: Validate Code
on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "Makefile"
      - ".github/workflows/*"
      - ".clang-format"
  pull_request:
    paths:
      - "**.c"
      - "**.h"
      - "Makefile"
      - ".github/workflows/*"
      - ".clang-format"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unit Tests
        run: make test

  memcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Valgrind
        run: sudo apt install valgrind
      - name: Valgrind Memcheck
        run: make memcheck

  lint:
    needs: [test, memcheck]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: sudo apt install clang-format-15
      - name: Run clang-format
        run: clang-format-15 --verbose -i $(git ls-files | grep -E ".+\.(c|h)")
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "style: format code with clang-format"
