name: Validate Code
on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "Makefile"
  pull_request:
    paths:
      - "**.c"
      - "**.h"
      - "Makefile"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unit Tests
        run: make test

  memcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Valgrind
        run: sudo apt install valgrind
      - name: Valgrind Memcheck
        run: |
          if make memcheck 2>&1 | grep -E "==[0-9]+==" ; then
            printf "\n[\x1B[1;31m FAILED MEMCHECK \x1B[0m]\n"
            exit 1
          else
            printf "\n[\x1B[1;32m PASSED MEMCHECK \x1B[0m]\n"
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clang Format
        uses: DoozyX/clang-format-lint-action@v0.15
        with:
          clangFormatVersion: 15
