name: Validate Code
on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "Makefile"
  pull_request:
    paths:
      - "**.c"
      - "**.h"
      - "Makefile"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unit Tests
        run: make test

  memcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Valgrind Memcheck
        run: |
          sudo apt install valgrind
          ! make memcheck 2>&1 | grep -E "(==[0-9]+==|FAIL|Failing: [1-9]+)"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clang Format
        uses: DoozyX/clang-format-lint-action@v0.15
        with:
          clangFormatVersion: 15
